name: fixpals
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  google_fonts: 2.3.1
  expandable: 5.0.1
  shared_preferences: 2.0.13
  http: 0.13.4
  razorpay_flutter: 1.2.9
  permission_handler: 8.2.5
  carousel_slider: 4.0.0
  flutter_map: 0.14.0
  latlong2: 0.8.1
  geolocator: 7.7.0
  sms_autofill: 2.2.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/json_files/
  uses-material-design: true

